SPACESHIP_GOENV_CURRENT_VERSION_SHOW="${SPACESHIP_GOENV_CURRENT_VERSION_SHOW=true}"
SPACESHIP_GOENV_CURRENT_VERSION_PREFIX="${SPACESHIP_GOENV_CURRENT_VERSION_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"}"
SPACESHIP_GOENV_CURRENT_VERSION_SUFFIX="${SPACESHIP_GOENV_CURRENT_VERSION_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"}"
SPACESHIP_GOENV_CURRENT_VERSION_SYMBOL="${SPACESHIP_GOENV_CURRENT_VERSION_SYMBOL="🐹 "}"
SPACESHIP_GOENV_CURRENT_VERSION_COLOR="${SPACESHIP_GOENV_CURRENT_VERSION_COLOR="cyan"}"

spaceship_goenv_current_version() {
  [[ $SPACESHIP_GOENV_CURRENT_VERSION_SHOW == false ]] && return

  local version=$(goenv_current_version)
  [[ $version == "none" ]] && return

  spaceship::section \
    "$SPACESHIP_GOENV_CURRENT_VERSION_COLOR" \
    "$SPACESHIP_GOENV_CURRENT_VERSION_PREFIX" \
    "${SPACESHIP_GOENV_CURRENT_VERSION_SYMBOL}${version}" \
    "$SPACESHIP_GOENV_CURRENT_VERSION_SUFFIX"
}
