SPACESHIP_NVM_CURRENT_VERSION_SHOW="${SPACESHIP_NVM_CURRENT_VERSION_SHOW=true}"
SPACESHIP_NVM_CURRENT_VERSION_PREFIX="${SPACESHIP_NVM_CURRENT_VERSION_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"}"
SPACESHIP_NVM_CURRENT_VERSION_SUFFIX="${SPACESHIP_NVM_CURRENT_VERSION_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"}"
SPACESHIP_NVM_CURRENT_VERSION_SYMBOL="${SPACESHIP_NVM_CURRENT_VERSION_SYMBOL="⬢ "}"
SPACESHIP_NVM_CURRENT_VERSION_DEFAULT_VERSION="${SPACESHIP_NVM_CURRENT_VERSION_DEFAULT_VERSION=""}"
SPACESHIP_NVM_CURRENT_VERSION_COLOR="${SPACESHIP_NVM_CURRENT_VERSION_COLOR="green"}"

spaceship_nvm_current_version() {
  [[ $SPACESHIP_NVM_CURRENT_VERSION_SHOW == false ]] && return

  local version=$(nvm_current_version)
  [[ $version == "none" ]] && return

  spaceship::section \
    "$SPACESHIP_NVM_CURRENT_VERSION_COLOR" \
    "$SPACESHIP_NVM_CURRENT_VERSION_PREFIX" \
    "${SPACESHIP_NVM_CURRENT_VERSION_SYMBOL}${version}" \
    "$SPACESHIP_NVM_CURRENT_VERSION_SUFFIX"
}
