SPACESHIP_RVM_CURRENT_VERSION_SHOW="${SPACESHIP_RVM_CURRENT_VERSION_SHOW=true}"
SPACESHIP_RVM_CURRENT_VERSION_PREFIX="${SPACESHIP_RVM_CURRENT_VERSION_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"}"
SPACESHIP_RVM_CURRENT_VERSION_SUFFIX="${SPACESHIP_RVM_CURRENT_VERSION_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"}"
SPACESHIP_RVM_CURRENT_VERSION_SYMBOL="${SPACESHIP_RVM_CURRENT_VERSION_SYMBOL="💎 "}"
SPACESHIP_RVM_CURRENT_VERSION_COLOR="${SPACESHIP_RVM_CURRENT_VERSION_COLOR="red"}"

spaceship_rvm_current_version() {
  [[ $SPACESHIP_RVM_CURRENT_VERSION_SHOW == false ]] && return

  local version=$(rvm_current_version)
  [[ $version == "none" ]] && return

  spaceship::section \
    "$SPACESHIP_RVM_CURRENT_VERSION_COLOR" \
    "$SPACESHIP_RVM_CURRENT_VERSION_PREFIX" \
    "${SPACESHIP_RVM_CURRENT_VERSION_SYMBOL}${version}" \
    "$SPACESHIP_RVM_CURRENT_VERSION_SUFFIX"
}
