zplug "bhilburn/powerlevel9k", use:powerlevel9k.zsh-theme

include "themes/powerlevel9k/segments/rvm_current_version"
include "themes/powerlevel9k/segments/nvm_current_version"
include "themes/powerlevel9k/segments/pyenv_current_version"
include "themes/powerlevel9k/segments/goenv_current_version"
include "themes/powerlevel9k/segments/docker_compose_status"

POWERLEVEL9K_MODE="nerdfont-complete"

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
  status
  dir
  vcs
  docker_compose_status
)

POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
  command_execution_time
  aws
  rvm_current_version
  nvm_current_version
  pyenv_current_version
  goenv_current_version
  background_jobs
)

POWERLEVEL9K_OK_ICON=""
POWERLEVEL9K_FAIL_ICON=""

POWERLEVEL9K_HOME_ICON=""
POWERLEVEL9K_HOME_SUB_ICON=""
POWERLEVEL9K_FOLDER_ICON=""
POWERLEVEL9K_ETC_ICON=""

POWERLEVEL9K_STATUS_CROSS="true"
POWERLEVEL9K_STATUS_SHOW_PIPESTATUS="false"

POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_SHORTEN_DELIMITER=".."

POWERLEVEL9K_VCS_CLEAN_FOREGROUND="white"
POWERLEVEL9K_VCS_CLEAN_BACKGROUND="dodgerblue1"
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND="grey11"
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND="orangered1"
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND="grey11"
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND="lightgoldenrod1"
POWERLEVEL9K_VCS_ACTIONFORMAT_FOREGROUND="white"
POWERLEVEL9K_VCS_ACTIONFORMAT_BACKGROUND="lightred"
POWERLEVEL9K_VCS_GIT_GITHUB_ICON=""
POWERLEVEL9K_VCS_GIT_ICON=""
POWERLEVEL9K_VCS_HG_ICON=""

POWERLEVEL9K_DOCKER_COMPOSE_STATUS_FOREGROUND="dodgerblue1"
POWERLEVEL9K_DOCKER_COMPOSE_STATUS_BACKGROUND="white"

POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=2
POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=0.15
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND="yellow"
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND="black"

POWERLEVEL9K_AWS_BACKGROUND="red1"
POWERLEVEL9K_AWS_FOREGROUND="white"
POWERLEVEL9K_AWS_ICON=""

POWERLEVEL9K_RVM_CURRENT_VERSION_BACKGROUND="red"
POWERLEVEL9K_RVM_CURRENT_VERSION_FOREGROUND="white"

POWERLEVEL9K_NVM_CURRENT_VERSION_BACKGROUND="034"
POWERLEVEL9K_NVM_CURRENT_VERSION_FOREGROUND="white"

POWERLEVEL9K_PYENV_CURRENT_VERSION_BACKGROUND="dodgerblue1"
POWERLEVEL9K_PYENV_CURRENT_VERSION_FOREGROUND="white"

POWERLEVEL9K_GOENV_CURRENT_VERSION_BACKGROUND="cyan"
POWERLEVEL9K_GOENV_CURRENT_VERSION_FOREGROUND="grey11"

POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE="true"
POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE_ALWAYS="true"
POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND="white"
POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND="dodgerblue1"
POWERLEVEL9K_BACKGROUND_JOBS_ICON=""
